# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: Instalando o .NET 5
  inputs:
    packageType: 'sdk'
    version: '5.0.100'
- script: dotnet --list-sdks
  displayName: Listar versões do .NET
- task: DotNetCoreCLI@2
  displayName: Executar testes
  inputs:
    command: 'test'
    projects: '**/APITemperatura.Especificacoes.csproj'
    testRunTitle: 'Teste da API de Temperatura'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    workingDirectory: './APITemperatura'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'apitemperatura-publish'
    publishLocation: 'Container'
- task: AzureRmWebAppDeployment@4
  displayName: Deployment no Azure
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Microsoft Azure Sponsorship(f3e7d90b-efba-4481-ac3d-d8df26b6235d)'
    appType: 'webApp'
    WebAppName: 'groffetestesarezzo'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'