# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: Listar versões do .NET
  displayName: dotnet --list-sdks
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/APITemperatura.Especificacoes.csproj'
    testRunTitle: 'Teste da API de Temperatura'