# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  displayName: Instalando o .NET 5
  inputs:
    packageType: 'sdk'
    version: '5.0.100'
- script: dotnet --list-sdks
  displayName: Listar versões do .NET
- task: DotNetCoreCLI@2
  displayName: Executar testes
  inputs:
    command: 'test'
    projects: '**/APITemperatura.Especificacoes.csproj'
    testRunTitle: 'Teste da API de Temperatura'